name: Run CI Pipeline
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build typescript
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: Unit tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
      - name: Integration tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test:integration
